= Demo for OpenTelemetry

This is a fork of the Quarkus Workshop as a demo for OpenTelemetry. Instead of spinning up a costly demo cluster, this could be run on a blank yet cheap cluster from the demo platform.

To make this works:

- Order a OpenShift Container Platform Cluster (Multi-Cloud) (single node is enough)
- Install these operators:
  * Red Hat OpenShift Dev Spaces
  * Red Hat build of OpenTelemetry
  * Tempo Operator
- Create a CheCluster in the Red Hat OpenShift Dev Spaces operator UI (keep everything default)
- Create a new DevSpace using this repository, wait a bit until the VSCode UI pop up
- In the UI, apply this manifest file `src/main/kubernetes/otel.yml` to create all otel components (Tempo and Otel collector)
- In the Ecosystem/Software Catalog of openshift ui, create a postgresql instance from `PostgreSQL (Ephemeral)` template
  * Install it in the admin-devspaces namespace
  * Keep everything default and fill these fields:
    * PostgreSQL Connection Username: `sa`
    * PostgreSQL Connection Password: `sa`
- Back to the vscode ui, run `mvn clean package -DskipTests` to deploy the app

After the app deployed, visit the jaeger ui to view the traces. Don't forget to visit the app first (at /datatable.html) to click some page first to create new traces.
